POST http://localhost:5000/api/product/create
Content-Type: application/json

{
    "title": "Ao so mi 2",
    "price": "150000",
    "image01": "https://res.cloudinary.com/dfupi3m0b/image/upload/v1659456460/web-ecommerce/tdfoutfzdaq3xtoqpjxz.jpg", 
    "image02": "https://res.cloudinary.com/dfupi3m0b/image/upload/v1659456533/web-ecommerce/yk7efhlbcdmfdvagkerb.jpg",
    "categorySlug": "ao-so-mi",
    "colors": ["red", "blue"], 
    "slug": "ao-so-mi-2",
    "size": ["s"],
    "description": "Ao dep" 
}


### Get all products
GET http://localhost:5000/api/product/all
Content-Type: application/json

### Update product
POST http://localhost:5000/api/product/edit/62fb4a0b91d70b79f1dc69e5
Content-Type: application/json

{
    "slug": "ao-thun-phong-cach-13"
}

### Get detail product
GET http://localhost:5000/api/product/detail/ao-thun-polo-07
Content-Type: application/json

### Delete product
DELETE  http://localhost:5000/api/product/delete/62f0df437e8af1c3e75af069
Content-Type: application/json

